Add error handling for when unreleased isn't spelled right or changelog has no changes.

diff --git a/scripts/version b/scripts/version
--- a/scripts/version
+++ b/scripts/version
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+if [ "$(grep -ic "unreleased" CHANGELOG.md)" -eq "0" ]; then
+  echo "(version) ERROR The changelog doesn't appear to include the string \"Unreleased\"."
+  echo "(version) ERROR Make sure the changelog is updated and Unreleased is spelled correctly, then try again."
+  exit 1
+fi
+
 releaseVersion="v${npm_package_version} ($(date +%Y-%m-%d))"
 
 sed -i "" "s/[Uu]nreleased/$releaseVersion/" CHANGELOG.md
